services:
  minecraft_server:
    container_name: minecraft_server
    image: laddertheory/mcs:$VERSION
    stdin_open: true  # -i
    tty: true         # -t
    ports:
      - 25565:25566
    volumes:
      - type: bind
        source: ./server
        target: /app/server